# -*- coding: utf-8 -*-
"""Mi exp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxFQbmGhAJRwBzHR0r6q4ZXa06scT-U4
"""

import streamlit as st
from PIL import Image

# Configuración de la página
st.set_page_config(
    page_title="Mi experiencia en programación",
    page_icon="💻",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# Colores personalizados
primary_color = "#84A59D"
background_color = "#F7F3E9"

# Estilo CSS personalizado
st.markdown(f"""
    <style>
        .stApp {{
            background-color: {background_color};
        }}
        .title {{
            font-size: 2.5em;
            font-weight: bold;
            color: {primary_color};
            text-align: center;
        }}
        .subtitle {{
            font-size: 1.5em;
            font-weight: lighter;
            color: #4A4E69;
            text-align: center;
        }}
        .paragraph {{
            font-size: 1.2em;
            line-height: 1.6;
            color: #333333;
            text-align: justify;
        }}
    </style>
""", unsafe_allow_html=True)

# Título principal
st.markdown('<div class="title">Mi experiencia aprendiendo a programar</div>', unsafe_allow_html=True)

# Párrafo principal
st.markdown("""
<div class="paragraph">
    Comencé a programar gracias al curso de Pensamiento Computacional en la universidad. Aunque estudio Comunicación Audiovisual, la programación despertó mi interés y decidí aprender más por mi cuenta. Empecé con Python siguiendo tutoriales en YouTube. Luego, mi curiosidad por el diseño UX y UI me llevó a aprender sobre interfaces en Figma, algo que estoy explorando actualmente. Aunque mi nivel de programación es básico, disfruto mucho el proceso de aprendizaje.
</div>
""", unsafe_allow_html=True)

# Imágenes
st.markdown('<div class="subtitle">Unas fotitos de mis bestias</div>', unsafe_allow_html=True)

# Cargar y mostrar imágenes
image1 = Image.open("WhatsApp Image 2024-11-27 at 12.32.02 PM.jpeg")
image2 = Image.open("WhatsApp Image 2024-11-27 at 12.32.53 PM.jpeg")

col1, col2 = st.columns(2)

with col1:
    st.image(image1, use_container_width=True)

with col2:
    st.image(image2, use_container_width=True)

# Mensaje final
st.markdown("""
<div class="subtitle">Gracias por leer mi historia 🐾✨</div>
""", unsafe_allow_html=True)